# masc_2015
python -m scripts.train --task_name=masc --session_name=masc_1 --output_model_path=/root/autodl-tmp/checkpoints/1.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --train_info_json=checkpoints/train_info_twitter2015-200_replayEwc_multi.json --num_labels=3 --epoch=5 --lr=1e-5 --step_size=2 --gamma=0.1 --replay=1 --ewc=1 --ewc_dir=/root/autodl-tmp/ewc_params
# mate_2015
python -m scripts.train --task_name=mate --session_name=mate_1 --pretrained_model_path=/root/autodl-tmp/checkpoints/1.pt --output_model_path=/root/autodl-tmp/checkpoints/1.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --num_labels=3 --train_info_json=checkpoints/train_info_twitter2015-200_replayEwc_multi.json --replay=1 --ewc=1 --ewc_dir=/root/autodl-tmp/ewc_params
# mner_2015
python -m scripts.train --task_name=mner --session_name=mner_1 --pretrained_model_path=/root/autodl-tmp/checkpoints/1.pt --output_model_path=/root/autodl-tmp/checkpoints/1.pt --train_text_file=data/MNER/twitter2015/train__.txt --test_text_file=data/MNER/twitter2015/test__.txt --dev_text_file=data/MNER/twitter2015/dev__.txt --num_labels=9 --train_info_json=checkpoints/train_info_twitter2015-200_replayEwc_multi.json --replay=1 --ewc=1 --ewc_dir=/root/autodl-tmp/ewc_params
# mabsa_2015
python -m scripts.train --task_name=mabsa --session_name=mabsa_1 --pretrained_model_path=/root/autodl-tmp/checkpoints/1.pt --output_model_path=/root/autodl-tmp/checkpoints/1.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --num_labels=7 --train_info_json=checkpoints/train_info_twitter2015-200_replayEwc_multi.json --replay=1 --epoch=20 --lr=5e-5 --step_size=10 --gamma=0.5 --ewc=1 --ewc_dir=/root/autodl-tmp/ewc_params
# mnre_2015
python -m scripts.train --task_name=mnre --session_name=mnre_1 --pretrained_model_path=/root/autodl-tmp/checkpoints/1.pt --output_model_path=/root/autodl-tmp/checkpoints/1.pt --train_text_file=data/MNRE/twitter2015/train__.txt --test_text_file=data/MNRE/twitter2015/test__.txt --dev_text_file=data/MNRE/twitter2015/dev__.txt --num_labels=23 --train_info_json=checkpoints/train_info_twitter2015-200_replayEwc_multi.json --replay=1 --ewc=1 --ewc_dir=/root/autodl-tmp/ewc_params

## masc_2017
#python -m scripts.train --task_name=masc --session_name=masc_2 --output_model_path=/root/autodl-tmp/checkpoints/model_masc_17_rE.pt --train_text_file=data/MASC/twitter2017/train__.txt --test_text_file=data/MASC/twitter2017/test__.txt --dev_text_file=data/MASC/twitter2017/dev__.txt --num_labels=3 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitter2017_replayEwc_multi.json --epoch=5 --lr=1e-5 --step_size=2 --gamma=0.1 --replay=1 --ewc=1
## mate_2017
#python -m scripts.train --task_name=mate --session_name=mate_2 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_masc_17_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mate_17_rE.pt --train_text_file=data/MASC/twitter2017/train__.txt --test_text_file=data/MASC/twitter2017/test__.txt --dev_text_file=data/MASC/twitter2017/dev__.txt --num_labels=3 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitter2017_replayEwc_multi.json --replay=1 --ewc=1
## mner_2017
#python -m scripts.train --task_name=mner --session_name=mner_2 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mate_17_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mner_17_rE.pt --train_text_file=data/MNER/twitter2017/train__.txt --test_text_file=data/MNER/twitter2017/test__.txt --dev_text_file=data/MNER/twitter2017/dev__.txt --num_labels=9 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitter2017_replayEwc_multi.json --replay=1 --ewc=1
## mabsa_2017
#python -m scripts.train --task_name=mabsa --session_name=mabsa_2 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mner_17_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mabsa_17_rE.pt --train_text_file=data/MASC/twitter2017/train__.txt --test_text_file=data/MASC/twitter2017/test__.txt --dev_text_file=data/MASC/twitter2017/dev__.txt --num_labels=7 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitter2017_replayEwc_multi.json --replay=1 --ewc=1
## mnre_2017
#python -m scripts.train --task_name=mnre --session_name=mnre_2 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mabsa_17_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mnre_17_rE.pt --train_text_file=data/MNRE/twitter2017/train__.txt --test_text_file=data/MNRE/twitter2017/test__.txt --dev_text_file=data/MNRE/twitter2017/dev__.txt --num_labels=23 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitter2017_replayEwc_multi.json --replay=1 --ewc=1
#
## masc_mix
#python -m scripts.train --task_name=masc --session_name=masc_3 --output_model_path=/root/autodl-tmp/checkpoints/model_masc_m_rE.pt --train_text_file=data/MASC/mix/train__.txt --test_text_file=data/MASC/mix/test__.txt --dev_text_file=data/MASC/mix/dev__.txt --num_labels=3 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitterMix_replayEwc_multi.json --epoch=5 --lr=1e-5 --step_size=2 --gamma=0.1 --replay=1 --ewc=1
## mate_mix
#python -m scripts.train --task_name=mate --session_name=mate_3 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_masc_m_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mate_m_rE.pt --train_text_file=data/MASC/mix/train__.txt --test_text_file=data/MASC/mix/test__.txt --dev_text_file=data/MASC/mix/dev__.txt --num_labels=3 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitterMix_replayEwc_multi.json --replay=1 --ewc=1
## mner_mix
#python -m scripts.train --task_name=mner --session_name=mner_3 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mate_m_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mner_m_rE.pt --train_text_file=data/MNER/mix/train__.txt --test_text_file=data/MNER/mix/test__.txt --dev_text_file=data/MNER/mix/dev__.txt --num_labels=9 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitterMix_replayEwc_multi.json --replay=1 --ewc=1
## mabsa_mix
#python -m scripts.train --task_name=mabsa --session_name=mabsa_3 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mner_m_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mabsa_m_rE.pt --train_text_file=data/MASC/mix/train__.txt --test_text_file=data/MASC/mix/test__.txt --dev_text_file=data/MASC/mix/dev__.txt --num_labels=7 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitterMix_replayEwc_multi.json --replay=1  --epoch=20 --lr=5e-5 --step_size=10 --gamma=0.5 --ewc=1
## mnre
#python -m scripts.train --task_name=mnre --session_name=mnre_3 --pretrained_model_path=/root/autodl-tmp/checkpoints/model_mabsa_m_rE.pt --output_model_path=/root/autodl-tmp/checkpoints/model_mnre_m_rE.pt --train_text_file=data/MNRE/mix/train__.txt --test_text_file=data/MNRE/mix/test__.txt --dev_text_file=data/MNRE/mix/dev__.txt --num_labels=23 --train_info_json=/root/autodl-tmp/checkpoints/train_info_twitterMix_replayEwc_multi.json --replay=1 --ewc=1
