source /d/ProgramData/anaconda3/etc/profile.d/conda.sh
conda activate pytorch
# masc_2015
python -m scripts.train --task_name=masc --session_name=masc_1 --output_model_path=checkpoints/model_masc.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --image_dir=data/MASC/twitter2015/images --train_info_json=checkpoints/train_info_200_replay_text.json --num_labels=3 --mode=text_only --replay=1
# mate_2015
python -m scripts.train --task_name=mate --session_name=mate_1 --pretrained_model_path=checkpoints/model_masc.pt --output_model_path=checkpoints/model_mate.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --image_dir=data/MASC/twitter2015/images --num_labels=3 --epochs=5 --lr=1e-5 --mode=text_only --train_info_json=checkpoints/train_info_200_replay_text.json --replay=1
# mner_2015
python -m scripts.train --task_name=mner --session_name=mner_1 --pretrained_model_path=checkpoints/model_mate.pt --output_model_path=checkpoints/model_mner.pt --train_text_file=data/MNER/twitter2015/train__.txt --test_text_file=data/MNER/twitter2015/test__.txt --dev_text_file=data/MNER/twitter2015/dev__.txt --image_dir=data/MNER/twitter2015/images --num_labels=9 --mode=text_only --train_info_json=checkpoints/train_info_200_replay_text.json --replay=1
# mnre
python -m scripts.train --task_name=mnre --session_name=mnre_1 --pretrained_model_path=checkpoints/model_mner.pt --output_model_path=checkpoints/model_mnre.pt --train_text_file=data/MNRE/mix/mnre_txt/train__.txt --test_text_file=data/MNRE/mix/mnre_txt/test__.txt --dev_text_file=data/MNRE/mix/mnre_txt/dev__.txt --image_dir=data/MNRE/mix/mnre_image --num_labels=23 --mode=text_only --train_info_json=checkpoints/train_info_200_replay_text.json --replay=1
# mabsa_2015
python -m scripts.train --task_name=mabsa --session_name=mabsa_1 --pretrained_model_path=checkpoints/model_mnre.pt --output_model_path=checkpoints/model_mabsa.pt --train_text_file=data/MASC/twitter2015/train__.txt --test_text_file=data/MASC/twitter2015/test__.txt --dev_text_file=data/MASC/twitter2015/dev__.txt --image_dir=data/MASC/twitter2015/images --num_labels=7 --mode=text_only --train_info_json=checkpoints/train_info_200_replay_text.json --replay=1